config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'mains#index'
    
    resources :users, only: [:show, :index]
    resources :reports, only: [:index, :new, :create, :edit, :update, :destroy] 
    resources :schools, only: [:index, :create]
    resources :students, only: [:index, :create ,:show, :edit, :update]
    resources :results, only: [:index, :new, :create, :edit, :update]
    get 'allresults' => 'results#allresult'
    get 'noresults' => 'results#noresult'
    resources :testresults, only: [:index, :new, :create, :edit, :update]
    get 'alltestresults' => 'testresults#alltestresult'
    get 'notestresults' => 'testresults#notestresult'
    resources :targets, only: [:new, :create, :destroy]
    resources :ittoexams, only: [:index, :new, :create, :edit, :update]
    resources :highfiles, only: [:new, :create, :destroy, :show]
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  belongs_to :student
  belongs_to :semester
  
  validates :student_id, presence: true
  validates :grade, presence: true
  validates :semester_id, presence: true
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    if params[:student_keyword].present? and params[:grade_keyword].present? and params[:semester_keyword].present?
      @results = Result.where(student_id: params[:student_keyword], grade: params[:grade_keyword], semester_id: params[:semester_keyword]).includes(:student, :user, :semester)
      @searchparameters = [params[:student_keyword], params[:grade_keyword], params[:semester_keyword]]
      student = Student.find(params[:student_keyword])
      @student = student.name
      semester = Semester.find(params[:semester_keyword])
      @semester = semester.semester
    else
      @aaa = 1
    end

    @students = Student.where(classifying: 2).order(classifying: :ASC, grade: :ASC, family_name_kana: :ASC)
    @semesters = Semester.all
  end

  def new
    @result = Result.new
    @searchparameters = [params[:student_keyword], params[:grade_keyword], params[:semester_keyword]]
  end

  def create
    Result.create(create_params)
    redirect_to results_path
  end

  def edit
    @result = Result.find(params[:id])
  end

  def update
    result = Result.find(params[:id])
    result.update(update_params)
    redirect_to results_path
  end

  def allresult
    if params[:grade_keyword].present? and params[:semester_keyword].present?
      @results = Result.where(grade: params[:grade_keyword]).includes(:user, :student, :semester)
      @results = @results.where(semester_id: params[:semester_keyword]).includes(:user, :student, :semester).order('students.classifying asc', 'students.grade asc', 'students.family_name_kana asc', 'students.given_name_kana asc')
    elsif params[:grade_keyword].present? and params[:semester_keyword].blank?
      @results = Result.where(grade: params[:grade_keyword]).includes(:user, :student, :semester).order('students.classifying asc', 'students.grade asc', 'students.family_name_kana asc', 'students.given_name_kana asc')
    elsif params[:grade_keyword].blank? and params[:semester_keyword].present?
      @results = Result.where(semester_id: params[:semester_keyword]).includes(:user, :student, :semester).order('students.classifying asc', 'students.grade asc', 'students.family_name_kana asc', 'students.given_name_kana asc')
    else
      @results = Result.all.includes(:student, :user, :semester).order('students.classifying asc', 'students.grade asc', 'students.family_name_kana asc', 'students.given_name_kana asc')
    end

    @semesters = Semester.all
  end

  def noresult
    if params[:grade_keyword].present? and params[:semester_keyword].present?
      @results = Result.where(grade: params[:grade_keyword]).includes(:user, :student, :semester)
      @results = @results.where(semester_id: params[:semester_keyword]).includes(:user, :student, :semester).order('students.classifying asc', 'students.grade asc', 'students.family_name_kana asc', 'students.given_name_kana asc')
    elsif params[:grade_keyword].present? and params[:semester_keyword].blank?
      @results = Result.where(grade: params[:grade_keyword]).includes(:user, :student, :semester).order('students.classifying asc', 'students.grade asc', 'students.family_name_kana asc', 'students.given_name_kana asc')
    elsif params[:grade_keyword].blank? and params[:semester_keyword].present?
      @results = Result.where(semester_id: params[:semester_keyword]).includes(:user, :student, :semester).order('students.classifying asc', 'students.grade asc', 'students.family_name_kana asc', 'students.given_name_kana asc')
    else
      @results = []
    end

    if params[:grade_keyword].present? and params[:semester_keyword].present?
      semester = Semester.find(params[:semester_keyword])
      semester = semester.semester
      @searchparameters = [params[:grade_keyword], semester]
    end

      # 未提出洗い出し
    result_ids = []
    @results.each do |result|
      result_ids << result.student_id
    end
    student_ids = []
    students = Student.where(classifying: 2)
    students.each do |student|
      student_ids << student.id
    end
    result_ids.each do |result_id|
      @none_student_ids = student_ids.delete_if { |id| id == result_id }
    end
    @none_students = []
    if @none_student_ids.present?
      @none_student_ids.each do |none_student_id|
        @none_students << Student.find(none_student_id)
        @none_students = @none_students.sort { |a, b| [a[:classifying], a[:grade], a[:family_name_kana], a[:given_name_kana]] <=> [b[:classifying], b[:grade], b[:family_name_kana], b[:given_name_kana]] }
      end
    else
      unless params[:grade_keyword].blank? and params[:semester_keyword].blank?
        @student_ids = []
        students = Student.where(classifying: 2)
        students.each do |student|
          @student_ids << student.id
        end
        @student_ids.each do |student_id|
          @none_students << Student.find(student_id)
          @none_students = @none_students.sort { |a, b| [a[:classifying], a[:grade], a[:family_name_kana], a[:given_name_kana]] <=> [b[:classifying], b[:grade], b[:family_name_kana], b[:given_name_kana]] }
        end
      end
    end

    @semesters = Semester.all
  end

  private

    def create_params
      params.require(:result).permit(:student_id, :grade, :semester_id, :english, :math, :japanese, :science, :social, :art, :pe, :techhome, :music, :total).merge(user_id: current_user.id)
    end

    def update_params
      params.require(:result).permit(:english, :math, :japanese, :science, :social, :art, :pe, :techhome, :music, :total).merge(user_id: current_user.id)
    end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_result.html.erb
<tr>
    <td><%= link_to "編集", edit_result_path(result.id), class: "edit_result_path"%></td>
    <td><a href="/students/<%= result.student.id %>" class="result_student_link"><%= result.student.student_info %></a></td>
    <td><%= result.grade %></td>
    <td><%= result.semester.semester %></td>
    <td><%= result.english %></td>
    <td><%= result.math %></td>
    <td><%= result.japanese %></td>
    <td><%= result.science %></td>
    <td><%= result.social %></td>
    <td><%= result.art %></td>
    <td><%= result.pe %></td>
    <td><%= result.techhome %></td>
    <td><%= result.music %></td>
    <td><%= result.total %></td>
    <td><%= result.user.name %></td>
</tr>

app/views/results/allresult.html.erb
<body class="result_body">
    <div class="search_group">
        <p class="search_title">通知表検索</p>
        <form method="get" action="/allresults">
            <select name="grade_keyword" class="search_box">
                <option value="">選択してください(学年)</option>
                <option value="1">1年</option>
                <option value="2">2年</option>
                <option value="3">3年</option>
            </select>
            <select name="semester_keyword" class="search_box">
                <option value="">選択してください(学期)</option>
                <% @semesters.each do |semester| %>
                    <option value="<%= semester.id %>"><%= semester.semester %></option>
                <% end %>
            </select>
            <p>
                <input type="submit" value="検索" class="search_btn">
                <%= link_to "一覧表示", allresults_path, class: "search_btn" %>
            </p>
        </form>
    </div>

    <p class="all_result_title">通知表一覧</p>
    <div class="all_result">
        <% if @results.present? %>
            <table border="1" class="result_table">
                <thead>
                    <tr>
                        <th></th>
                        <th>生徒氏名</th>
                        <th>学年</th>
                        <th>学期</th>
                        <th>英語</th>
                        <th>数学</th>
                        <th>国語</th>
                        <th>理科</th>
                        <th>社会</th>
                        <th>美術</th>
                        <th>体育</th>
                        <th>技家</th>
                        <th>音楽</th>
                        <th>合計</th>
                        <th>登録者</th>
                    </tr>
                </thead>
                <tbody>
                    <%= render @results %>
                </tbody>
            </table>
        <% end %>
    </div>
</div>
    

app/views/results/edit.html.erb
<body class="result_new_body">
    <div class="result_form">
        <p class="search_title result_new_title">成績編集</p>
        <%= form_for @result do |f| %>
        <div class="report_form_group">
            <%= f.label :student_id, '生徒'%>
            <%= f.collection_select :student_id , Student.order(classifying: :ASC, grade: :ASC, family_name_kana: :ASC), :id, :name, {include_blank: '選択してください'}, { class: 'form-control' , required: true, disabled: true } %>
        </div>
        <div class="report_form_group">
            <%= f.label :grade, '学年' %>
            <%= f.select :grade, {'1': 1, '2': 2, '3': 3}, { include_blank: '選択してください'}, { class: 'form-control' , required: true, disabled: true } %>
        </div>
        <div class="report_form_group">
            <%= f.label :semester_id, '学期'%>
            <%= f.collection_select :semester_id, Semester.all, :id, :semester, {include_blank: '選択してください'}, { class: 'form-control' , required: true, disabled: true }%>
        </div>
        <div class="result_num_form">
            <div class="report_form_group">
                <%= f.label :japanese, '国語' %>
                <%= f.radio_button :japanese, "1" %>1
                <%= f.radio_button :japanese, "2" %>2
                <%= f.radio_button :japanese, "3" %>3
                <%= f.radio_button :japanese, "4" %>4
                <%= f.radio_button :japanese, "5" %>5
            </div>
            <div class="report_form_group">
                <%= f.label :social, '社会' %>
                <%= f.radio_button :social, "1" %>1
                <%= f.radio_button :social, "2" %>2
                <%= f.radio_button :social, "3" %>3
                <%= f.radio_button :social, "4" %>4
                <%= f.radio_button :social, "5" %>5
            </div>
            <div class="report_form_group">
                <%= f.label :math, '数学' %>
                <%= f.radio_button :math, "1" %>1
                <%= f.radio_button :math, "2" %>2
                <%= f.radio_button :math, "3" %>3
                <%= f.radio_button :math, "4" %>4
                <%= f.radio_button :math, "5" %>5
            </div>
            <div class="report_form_group">
                <%= f.label :science, '理科' %>
                <%= f.radio_button :science, "1" %>1
                <%= f.radio_button :science, "2" %>2
                <%= f.radio_button :science, "3" %>3
                <%= f.radio_button :science, "4" %>4
                <%= f.radio_button :science, "5" %>5
            </div>
            <div class="report_form_group">
                <%= f.label :music, '音楽' %>
                <%= f.radio_button :music, "1" %>1
                <%= f.radio_button :music, "2" %>2
                <%= f.radio_button :music, "3" %>3
                <%= f.radio_button :music, "4" %>4
                <%= f.radio_button :music, "5" %>5
            </div>
            <div class="report_form_group">
                <%= f.label :art, '美術' %>
                <%= f.radio_button :art, "1" %>1
                <%= f.radio_button :art, "2" %>2
                <%= f.radio_button :art, "3" %>3
                <%= f.radio_button :art, "4" %>4
                <%= f.radio_button :art, "5" %>5
            </div>
            <div class="report_form_group">
                <%= f.label :pe, '体育' %>
                <%= f.radio_button :pe, "1" %>1
                <%= f.radio_button :pe, "2" %>2
                <%= f.radio_button :pe, "3" %>3
                <%= f.radio_button :pe, "4" %>4
                <%= f.radio_button :pe, "5" %>5
            </div>
            <div class="report_form_group">
                <%= f.label :techhome, '技家' %>
                <%= f.radio_button :techhome, "1" %>1
                <%= f.radio_button :techhome, "2" %>2
                <%= f.radio_button :techhome, "3" %>3
                <%= f.radio_button :techhome, "4" %>4
                <%= f.radio_button :techhome, "5" %>5
            </div>
            <div class="report_form_group">
                <%= f.label :english, '英語' %>
                <%= f.radio_button :english, "1" %>1
                <%= f.radio_button :english, "2" %>2
                <%= f.radio_button :english, "3" %>3
                <%= f.radio_button :english, "4" %>4
                <%= f.radio_button :english, "5" %>5
            </div>
            <div class="report_form_group report_form_group_total">
                <%= f.label :total, '合計'%>
                <%= f.number_field :total , class: 'form-control', min: 9, max: 45 %>
            </div>
            <div class="report_form_group">
                <%= f.submit '登録', class: 'btn_signup result_new_btn' %>
            </div>
        </div>
    <% end %>
</body>

app/views/results/index.html.erb
<body class="result_body">
    <div class="search_group search_group_result">
        <p class="search_title">成績検索</p>
        <form method="get" action="/results">
            <select name="student_keyword" class="result_search_box" required>
                <option value="">生徒氏名を選択してください</option>
                <% @students.each do |student| %>
                    <option value="<%= student.id %>"><%= student.student_info %></option>
                <% end %>
            </select>
            <p class="search_radio">学年
                <input type="radio" name="grade_keyword" value="1" required>1
                <input type="radio" name="grade_keyword" value="2">2
                <input type="radio" name="grade_keyword" value="3">3
            </p>
            <p class="search_radio search_radio_test">学期
                <% @semesters.each do |semester| %>
                    <input type="radio" name="semester_keyword" value="<%= semester.id %>" required><%= semester.semester %>
                <% end %>
            <p>
                <input type="submit" value="検索" class="search_btn">
            </p>
        </form>
    </div>
    <div class="all_result">
        <% if @results.present? %>
            <table border="1" class="result_table">
                <thead>
                    <tr>
                        <th></th>
                        <th>生徒氏名</th>
                        <th>学年</th>
                        <th>学期</th>
                        <th>英語</th>
                        <th>数学</th>
                        <th>国語</th>
                        <th>理科</th>
                        <th>社会</th>
                        <th>美術</th>
                        <th>体育</th>
                        <th>技家</th>
                        <th>音楽</th>
                        <th>合計</th>
                        <th>登録者</th>
                    </tr>
                </thead>
                <tbody>
                    <%= render @results %>
                </tbody>
            </table>
        <% elsif @aaa.present? %>
            <a class="search_alert">まずは検索をしてください。</a>
        <% else %>
            <p class="search_nothing_alert">
                <%= @student %>さん　<%= @searchparameters[1] %>年　<%= @semester %>　の検索結果がありませんでした。
            </p>
            <form method="get" action="/results/new">
                <input type="hidden" name="student_keyword" value="<%= @searchparameters[0] %>">
                <input type="hidden" name="grade_keyword" value="<%= @searchparameters[1] %>">
                <input type="hidden" name="semester_keyword" value="<%= @searchparameters[2] %>">
                <input type="submit" value="新規登録" class="search_btn">
            </form>
        <% end %>
    </div>
</body>

app/views/results/new.html.erb
<body class="result_new_body">
    <div class="result_form">
         <p class="search_title result_new_title">成績追加</p>
        <%= form_for @result do |f| %>
            <div class="report_form_group">
                <%= f.label :student_id, '生徒'%>
                <%= f.collection_select :student_id , Student.where(classifying: 2).order(classifying: :ASC, grade: :ASC, family_name_kana: :ASC), :id, :name, {include_blank: '選択してください', selected: @searchparameters[0]}, { class: 'form-control' , required: true, disabled: true} %>
                <%= f.hidden_field :student_id, value: @searchparameters[0] %>
            </div>
            <div class="report_form_group">
                <%= f.label :grade, '学年' %>
                <%= f.select :grade, {'1': 1, '2': 2, '3': 3}, { include_blank: '選択してください', selected: @searchparameters[1]}, { class: 'form-control' , required: true , disabled: true} %>
                <%= f.hidden_field :grade, value: @searchparameters[1] %>
            </div>
            <div class="report_form_group">
                <%= f.label :semester_id, '学期'%>
                <%= f.collection_select :semester_id, Semester.all, :id, :semester, {include_blank: '選択してください', selected: @searchparameters[2]}, { class: 'form-control' , required: true , disabled: true}%>
                <%= f.hidden_field :semester_id, value: @searchparameters[2] %>
            </div>
        <div class="result_num_form">
            <div class="report_form_group">
                <%= f.label :japanese, '国語' %>
                <%= f.radio_button :japanese, "1" %>1
                <%= f.radio_button :japanese, "2" %>2
                <%= f.radio_button :japanese, "3" %>3
                <%= f.radio_button :japanese, "4" %>4
                <%= f.radio_button :japanese, "5" %>5
            </div>
            <div class="report_form_group">
                <%= f.label :social, '社会' %>
                <%= f.radio_button :social, "1" %>1
                <%= f.radio_button :social, "2" %>2
                <%= f.radio_button :social, "3" %>3
                <%= f.radio_button :social, "4" %>4
                <%= f.radio_button :social, "5" %>5
            </div>
            <div class="report_form_group">
                <%= f.label :math, '数学' %>
                <%= f.radio_button :math, "1" %>1
                <%= f.radio_button :math, "2" %>2
                <%= f.radio_button :math, "3" %>3
                <%= f.radio_button :math, "4" %>4
                <%= f.radio_button :math, "5" %>5
            </div>
            <div class="report_form_group">
                <%= f.label :science, '理科' %>
                <%= f.radio_button :science, "1" %>1
                <%= f.radio_button :science, "2" %>2
                <%= f.radio_button :science, "3" %>3
                <%= f.radio_button :science, "4" %>4
                <%= f.radio_button :science, "5" %>5
            </div>
            <div class="report_form_group">
                <%= f.label :music, '音楽' %>
                <%= f.radio_button :music, "1" %>1
                <%= f.radio_button :music, "2" %>2
                <%= f.radio_button :music, "3" %>3
                <%= f.radio_button :music, "4" %>4
                <%= f.radio_button :music, "5" %>5
            </div>
            <div class="report_form_group">
                <%= f.label :art, '美術' %>
                <%= f.radio_button :art, "1" %>1
                <%= f.radio_button :art, "2" %>2
                <%= f.radio_button :art, "3" %>3
                <%= f.radio_button :art, "4" %>4
                <%= f.radio_button :art, "5" %>5
            </div>
            <div class="report_form_group">
                <%= f.label :pe, '体育' %>
                <%= f.radio_button :pe, "1" %>1
                <%= f.radio_button :pe, "2" %>2
                <%= f.radio_button :pe, "3" %>3
                <%= f.radio_button :pe, "4" %>4
                <%= f.radio_button :pe, "5" %>5
            </div>
            <div class="report_form_group">
                <%= f.label :techhome, '技家' %>
                <%= f.radio_button :techhome, "1" %>1
                <%= f.radio_button :techhome, "2" %>2
                <%= f.radio_button :techhome, "3" %>3
                <%= f.radio_button :techhome, "4" %>4
                <%= f.radio_button :techhome, "5" %>5
            </div>
            <div class="report_form_group">
                <%= f.label :english, '英語' %>
                <%= f.radio_button :english, "1" %>1
                <%= f.radio_button :english, "2" %>2
                <%= f.radio_button :english, "3" %>3
                <%= f.radio_button :english, "4" %>4
                <%= f.radio_button :english, "5" %>5
            </div>
            <div class="report_form_group report_form_group_total">
                <%= f.label :total, '合計'%>
                <%= f.number_field :total , class: 'form-control', min: 9, max: 45 %>
            </div>
            <div class="report_form_group">
                <%= f.submit '登録', class: 'btn_signup result_new_btn' %>
            </div>
        </div>
    <% end %>
    </div>
</body>

app/views/results/noresult.html.erb
<body class="result_body">
    <div class="search_group">
        <p class="search_title">通知表未提出検索</p>
        <form method="get" action="/noresults">
            <select name="grade_keyword" class="search_box">
                <option value="">選択してください(学年)</option>
                <option value="1">1年</option>
                <option value="2">2年</option>
                <option value="3">3年</option>
            </select>
            <select name="semester_keyword" class="search_box">
                <option value="">選択してください(学期)</option>
                <% @semesters.each do |semester| %>
                    <option value="<%= semester.id %>"><%= semester.semester %></option>
                <% end %>
            </select>
            <p>
                <input type="submit" value="検索" class="search_btn">
            </p>
        </form>
    </div>
    
    <div class="menu_group">
        <%= link_to "通知表検索", allresults_path, class: "report_menu_item" %>
    </div>
    
    <% if @searchparameters.present? %>
        <p class="all_result_title"><%= @searchparameters[0]%>年　<%= @searchparameters[1]%>　の未提出者</p>
    <% end %>
    <div class="all_result">
        <% if @none_students.present? %>
            <table border="1" class="noresult_table">
                <thead>
                    <tr>
                        <th>生徒ID</th>
                        <th>生徒氏名</th>
                    </tr>
                </thead>
                <tbody>
                    <% @none_students.each do |none_student| %>
                    <tr>
                        <td><%= none_student.id %></td>
                        <td><a href="/students/<%= none_student.id %>" class="result_student_link"><%= none_student.student_info %></a></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        <% end %>
    </div>
</div>
    