config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'mains#index'
    
    resources :users, only: [:show, :index]
    resources :reports, only: [:index, :new, :create, :edit, :update, :destroy] 
    resources :schools, only: [:index, :create]
    resources :students, only: [:index, :create ,:show, :edit, :update]
    resources :results, only: [:index, :new, :create, :edit, :update]
    get 'allresults' => 'results#allresult'
    get 'noresults' => 'results#noresult'
    resources :testresults, only: [:index, :new, :create, :edit, :update]
    get 'alltestresults' => 'testresults#alltestresult'
    get 'notestresults' => 'testresults#notestresult'
    resources :targets, only: [:new, :create, :destroy]
    resources :ittoexams, only: [:index, :new, :create, :edit, :update]
    resources :highfiles, only: [:new, :create, :destroy, :show]
end

app/models/testresult.rb
class Testresult < ApplicationRecord
  belongs_to :user
  belongs_to :student
  belongs_to :test
  
  validates :student_id, presence: true
  validates :grade, presence: true
  validates :test_id, presence: true
end

app/controllers/testresults_controller.rb
class TestresultsController < ApplicationController
  def index
    if params[:student_keyword].present? and params[:grade_keyword].present? and params[:test_keyword].present?
      @testresults = Testresult.where(student_id: params[:student_keyword], grade: params[:grade_keyword], test_id: params[:test_keyword]).includes(:student, :user, :test)
      @searchparameters = [params[:student_keyword], params[:grade_keyword], params[:test_keyword]]
      student = Student.find(params[:student_keyword])
      @student = student.name
      test = Test.find(params[:test_keyword])
      @test = test.test
    else
      @aaa = 1
    end

    @students = Student.where(classifying: 2).order(classifying: :ASC, grade: :ASC, family_name_kana: :ASC)
    @tests = Test.all
  end

  def new
    @testresult = Testresult.new
    @searchparameters = [params[:student_keyword], params[:grade_keyword], params[:test_keyword]]
  end

  def create
    Testresult.create(create_params)
    redirect_to testresults_path
  end

  def edit
    @testresult = Testresult.find(params[:id])
  end

  def update
    testresult = Testresult.find(params[:id])
    testresult.update(update_params)
    redirect_to testresults_path
  end

  def alltestresult
    if params[:grade_keyword].present? and params[:test_keyword].present?
      @testresults = Testresult.where(grade: params[:grade_keyword]).includes(:user, :student, :test)
      @testresults = @testresults.where(test_id: params[:test_keyword]).includes(:user, :student, :test).order('students.classifying asc', 'students.grade asc', 'students.family_name_kana asc', 'students.given_name_kana asc')
    elsif params[:grade_keyword].present? and params[:test_keyword].blank?
      @testresults = Testresult.where(grade: params[:grade_keyword]).includes(:user, :student, :test).order('students.classifying asc', 'students.grade asc', 'students.family_name_kana asc', 'students.given_name_kana asc')
    elsif params[:grade_keyword].blank? and params[:test_keyword].present?
      @testresults = Testresult.where(test_id: params[:test_keyword]).includes(:user, :student, :test).order('students.classifying asc', 'students.grade asc', 'students.family_name_kana asc', 'students.given_name_kana asc')
    else
      @testresults = Testresult.all.includes(:student, :user, :test).order('students.classifying asc', 'students.grade asc', 'students.family_name_kana asc', 'students.given_name_kana asc')
    end

    @tests = Test.all
  end

  def notestresult
    if params[:grade_keyword].present? and params[:test_keyword].present?
      @testresults = Testresult.where(grade: params[:grade_keyword]).includes(:user, :student, :test)
      @testresults = @testresults.where(test_id: params[:test_keyword]).includes(:user, :student, :test).order('students.classifying asc', 'students.grade asc', 'students.family_name_kana asc', 'students.given_name_kana asc')
    elsif params[:grade_keyword].present? and params[:test_keyword].blank?
      @testresults = Testresult.where(grade: params[:grade_keyword]).includes(:user, :student, :test).order('students.classifying asc', 'students.grade asc', 'students.family_name_kana asc', 'students.given_name_kana asc')
    elsif params[:grade_keyword].blank? and params[:test_keyword].present?
      @testresults = Testresult.where(test_id: params[:test_keyword]).includes(:user, :student, :test).order('students.classifying asc', 'students.grade asc', 'students.family_name_kana asc', 'students.given_name_kana asc')
    else
      @testresults = []
    end

    if params[:grade_keyword].present? and params[:test_keyword].present?
      test = Test.find(params[:test_keyword])
      test = test.test
      @searchparameters = [params[:grade_keyword], test]
    end

      # 未提出洗い出し
    result_ids = []
    @testresults.each do |result|
      result_ids << result.student_id
    end
    student_ids = []
    students = Student.where(classifying: 2)
    students.each do |student|
      student_ids << student.id
    end
    result_ids.each do |result_id|
      @none_student_ids = student_ids.delete_if { |id| id == result_id }
    end
    @none_students = []
    if @none_student_ids.present?
      @none_student_ids.each do |none_student_id|
        @none_students << Student.find(none_student_id)
        @none_students = @none_students.sort { |a, b| [a[:classifying], a[:grade], a[:family_name_kana], a[:given_name_kana]] <=> [b[:classifying], b[:grade], b[:family_name_kana], b[:given_name_kana]] }
      end
    else
      unless params[:grade_keyword].blank? and params[:test_keyword].blank?
        @student_ids = []
        students = Student.where(classifying: 2)
        students.each do |student|
          @student_ids << student.id
        end
        @student_ids.each do |student_id|
          @none_students << Student.find(student_id)
          @none_students = @none_students.sort { |a, b| [a[:classifying], a[:grade], a[:family_name_kana], a[:given_name_kana]] <=> [b[:classifying], b[:grade], b[:family_name_kana], b[:given_name_kana]] }
        end
      end
    end

    @tests = Test.all
  end

  private

    def create_params
      params.require(:testresult).permit(:student_id, :grade, :test_id, :english, :math, :japanese, :science, :social, :art, :pe, :techhome, :music, :fivetotal, :classrank, :graderank).merge(user_id: current_user.id)
    end

    def update_params
      params.require(:testresult).permit(:english, :math, :japanese, :science, :social, :art, :pe, :techhome, :music, :fivetotal, :classrank, :graderank).merge(user_id: current_user.id)
    end
end

app/helpers/testresults_helper.rb
module TestresultsHelper
end

app/views/testresults/_testresult.html.erb
<tr>
    <td><%= link_to "編集", edit_testresult_path(testresult.id), class: "edit_result_path"%></td>
    <td><a href="/students/<%= testresult.student.id %>" class="result_student_link"><%= testresult.student.student_info %></a></td>
    <td><%= testresult.grade %></td>
    <td><%= testresult.test.test %></td>
    <td><%= testresult.english %></td>
    <td><%= testresult.math %></td>
    <td><%= testresult.japanese %></td>
    <td><%= testresult.science %></td>
    <td><%= testresult.social %></td>
    <td><%= testresult.art %></td>
    <td><%= testresult.pe %></td>
    <td><%= testresult.techhome %></td>
    <td><%= testresult.music %></td>
    <td><%= testresult.fivetotal %></td>
    <td><%= testresult.classrank %></td>
    <td><%= testresult.graderank %></td>
    <td><%= testresult.user.name %></td>
</tr>

app/views/testresults/alltestresult.html.erb
<body class="result_body">

    <div class="search_group">
        <p class="search_title">定期試験結果検索</p>
        <form method="get" action="/alltestresults">
            <select name="grade_keyword" class="search_box">
                <option value="">選択してください(学年)</option>
                <option value="1">1年</option>
                <option value="2">2年</option>
                <option value="3">3年</option>
            </select>
            <select name="test_keyword" class="search_box">
                <option value="">選択してください(学期)</option>
                <% @tests.each do |test| %>
                    <option value="<%= test.id %>"><%= test.test %></option>
                <% end %>
            </select>
            <p>
                <input type="submit" value="検索" class="search_btn">
                <%= link_to "一覧表示", alltestresults_path, class: "search_btn" %>
            </p>
        </form>
    </div>
    
    <div class="menu_group">
        <%= link_to "未提出者検索", notestresults_path, class: "report_menu_item" %>
    </div>

    <p class="all_result_title">定期試験結果一覧</p>
    <div class="all_result">
        <% if @testresults.present? %>
            <table border="1" class="result_table">
                <thead>
                    <tr>
                        <th></th>
                        <th>生徒氏名</th>
                        <th>学年</th>
                        <th>学期</th>
                        <th>英語</th>
                        <th>数学</th>
                        <th>国語</th>
                        <th>理科</th>
                        <th>社会</th>
                        <th>美術</th>
                        <th>体育</th>
                        <th>技家</th>
                        <th>音楽</th>
                        <th>5教科合計</th>
                        <th>クラス順位</th>
                        <th>学年順位</th>
                        <th>登録者</th>
                    </tr>
                </thead>
                <tbody>
                    <%= render @testresults %>
                </tbody>
            </table>
        <% end %>
    </div>
</div>

app/views/testresults/edit.html.erb
<body class="result_new_body">
    <div class="result_form">
        <p class="search_title result_new_title">試験結果編集</p>
        <%= form_for @testresult do |f| %>
            <div class="report_form_group">
                <%= f.label :student_id, '生徒'%>
                <%= f.collection_select :student_id , Student.order(classifying: :ASC, grade: :ASC, family_name_kana: :ASC), :id, :name, {include_blank: '選択してください'}, { class: 'form-control' , required: true, disabled: true } %>
            </div>
            <div class="report_form_group">
                <%= f.label :grade, '学年' %>
                <%= f.select :grade, {'1': 1, '2': 2, '3': 3}, { include_blank: '選択してください'}, { class: 'form-control' , required: true, disabled: true } %>
            </div>
            <div class="report_form_group">
                <%= f.label :test_id, '試験名'%>
                <%= f.collection_select :test_id, Test.all, :id, :test, {include_blank: '選択してください'}, { class: 'form-control' , required: true, disabled: true }%>
            </div>
            <div class="result_num_form">
                <div class="report_form_group">
                    <%= f.label :japanese, '国語' %>
                    <%= f.number_field :japanese , class: 'form-control', min: 0, max: 100 %>
                    
                </div>
                <div class="report_form_group">
                    <%= f.label :social, '社会' %>
                    <%= f.number_field :social , class: 'form-control', min: 0, max: 100 %>
                </div>
                <div class="report_form_group">
                    <%= f.label :math, '数学' %>
                    <%= f.number_field :math, class: 'form-control', min: 0, max: 100 %>
                </div>
                <div class="report_form_group">
                    <%= f.label :science, '理科' %>
                    <%= f.number_field :science , class: 'form-control', min: 0, max: 100 %>
                </div>
                <div class="report_form_group">
                    <%= f.label :music, '音楽' %>
                    <%= f.number_field :music , class: 'form-control', min: 0, max: 100 %>
                </div>
                <div class="report_form_group">
                    <%= f.label :art, '美術' %>
                    <%= f.number_field :art , class: 'form-control', min: 0, max: 100 %>
                </div>
                <div class="report_form_group">
                    <%= f.label :pe, '体育' %>
                    <%= f.number_field :pe, class: 'form-control', min: 0, max: 100 %>
                </div>
                <div class="report_form_group">
                    <%= f.label :techhome, '技家' %>
                    <%= f.number_field :techhome , class: 'form-control', min: 0, max: 100 %>
                </div>
                <div class="report_form_group">
                    <%= f.label :english, '英語' %>
                    <%= f.number_field :english , class: 'form-control', min: 0, max: 100 %>
                </div>
                <div class="report_form_group">
                    <%= f.label :fivetotal, '5教科合計'%>
                    <%= f.number_field :fivetotal , class: 'form-control', min: 0, max: 500 %>
                </div>
                <div class="report_form_group">
                    <%= f.label :classrank, 'クラス順位'%>
                    <%= f.number_field :classrank , class: 'form-control', min: 1, max: 500 %>
                </div>
                <div class="report_form_group">
                    <%= f.label :graderank, '学年順位'%>
                    <%= f.number_field :graderank , class: 'form-control', min: 1, max: 500 %>
                </div>
                <div class="report_form_group">
                    <%= f.submit '登録', class: 'btn_signup result_new_btn' %>
                </div>
            </div>
        <% end %>
    </div>
</body>

app/views/testresults/index.html.erb
<body class="result_body">
    <div class="search_group">
        <p class="search_title">試験結果検索</p>
        <form method="get" action="/testresults">
            <select name="student_keyword" class="result_search_box" required>
                <option value="">生徒氏名を選択してください</option>
                <% @students.each do |student| %>
                    <option value="<%= student.id %>"><%= student.student_info %></option>
                <% end %>
            </select>
            <p class="search_radio">学年
                <input type="radio" name="grade_keyword" value="1" required>1
                <input type="radio" name="grade_keyword" value="2">2
                <input type="radio" name="grade_keyword" value="3">3
            </p>
            <p class="search_radio search_radio_test">試験名
                <% @tests.each do |test| %>
                    <input type="radio" name="test_keyword" value="<%= test.id %>" required><%= test.test %>
                <% end %>
            <p>
                <input type="submit" value="検索" class="search_btn">
            </p>
        </form>
    </div>
    <div class="all_result">
        <% if @testresults.present? %>
            <table border="1" class="result_table">
                <thead>
                    <tr>
                        <th></th>
                        <th>生徒氏名</th>
                        <th>学年</th>
                        <th>学期</th>
                        <th>英語</th>
                        <th>数学</th>
                        <th>国語</th>
                        <th>理科</th>
                        <th>社会</th>
                        <th>美術</th>
                        <th>体育</th>
                        <th>技家</th>
                        <th>音楽</th>
                        <th>5教科合計</th>
                        <th>クラス順位</th>
                        <th>学年順位</th>
                        <th>登録者</th>
                    </tr>
                </thead>
                <tbody>
                    <%= render @testresults %>
                </tbody>
            </table>
        <% elsif @aaa.present? %>
            <a class="search_alert">まずは検索をしてください。</a>
        <% else %>
            <p class="search_nothing_alert">
                <%= @student %>さん　<%= @searchparameters[1] %>年　<%= @test %>　の検索結果がありませんでした。
            </p>
            <form method="get" action="/testresults/new">
                <input type="hidden" name="student_keyword" value="<%= @searchparameters[0] %>">
                <input type="hidden" name="grade_keyword" value="<%= @searchparameters[1] %>">
                <input type="hidden" name="test_keyword" value="<%= @searchparameters[2] %>">
                <input type="submit" value="新規登録" class="search_btn">
            </form>
        <% end %>
    </div>
</body>

app/views/testresults/new.html.erb
<body class="result_new_body">
    <div class="result_form">
        <p class="search_title result_new_title">試験結果追加</p>
        <%= form_for @testresult do |f| %>
            <div class="report_form_group">
                <%= f.label :student_id, '生徒'%>
                <%= f.collection_select :student_id , Student.order(classifying: :ASC, grade: :ASC, family_name_kana: :ASC), :id, :name, {include_blank: '選択してください', selected: @searchparameters[0]}, { class: 'form-control' , required: true, disabled: true } %>
                <%= f.hidden_field :student_id, value: @searchparameters[0] %>
            </div>
            <div class="report_form_group">
                <%= f.label :grade, '学年' %>
                <%= f.select :grade, {'1': 1, '2': 2, '3': 3}, { include_blank: '選択してください', selected: @searchparameters[1]}, { class: 'form-control' , required: true, disabled: true } %>
                <%= f.hidden_field :grade, value: @searchparameters[1] %>
            </div>
            <div class="report_form_group">
                <%= f.label :test_id, '試験名'%>
                <%= f.collection_select :test_id, Test.all, :id, :test, {include_blank: '選択してください', selected: @searchparameters[2]}, { class: 'form-control' , required: true, disabled: true }%>
                <%= f.hidden_field :test_id, value: @searchparameters[2] %>
            </div>
            <div class="result_num_form">
                <div class="report_form_group">
                    <%= f.label :japanese, '国語' %>
                    <%= f.number_field :japanese , class: 'form-control', min: 0, max: 100 %>
                    
                </div>
                <div class="report_form_group">
                    <%= f.label :social, '社会' %>
                    <%= f.number_field :social , class: 'form-control', min: 0, max: 100 %>
                </div>
                <div class="report_form_group">
                    <%= f.label :math, '数学' %>
                    <%= f.number_field :math, class: 'form-control', min: 0, max: 100 %>
                </div>
                <div class="report_form_group">
                    <%= f.label :science, '理科' %>
                    <%= f.number_field :science , class: 'form-control', min: 0, max: 100 %>
                </div>
                <div class="report_form_group">
                    <%= f.label :music, '音楽' %>
                    <%= f.number_field :music , class: 'form-control', min: 0, max: 100 %>
                </div>
                <div class="report_form_group">
                    <%= f.label :art, '美術' %>
                    <%= f.number_field :art , class: 'form-control', min: 0, max: 100 %>
                </div>
                <div class="report_form_group">
                    <%= f.label :pe, '体育' %>
                    <%= f.number_field :pe, class: 'form-control', min: 0, max: 100 %>
                </div>
                <div class="report_form_group">
                    <%= f.label :techhome, '技家' %>
                    <%= f.number_field :techhome , class: 'form-control', min: 0, max: 100 %>
                </div>
                <div class="report_form_group">
                    <%= f.label :english, '英語' %>
                    <%= f.number_field :english , class: 'form-control', min: 0, max: 100 %>
                </div>
                <div class="report_form_group">
                    <%= f.label :fivetotal, '5教科合計'%>
                    <%= f.number_field :fivetotal , class: 'form-control', min: 0, max: 500 %>
                </div>
                <div class="report_form_group">
                    <%= f.label :classrank, 'クラス順位'%>
                    <%= f.number_field :classrank , class: 'form-control', min: 1, max: 500 %>
                </div>
                <div class="report_form_group">
                    <%= f.label :graderank, '学年順位'%>
                    <%= f.number_field :graderank , class: 'form-control', min: 1, max: 500 %>
                </div>
                <div class="report_form_group">
                    <%= f.submit '登録', class: 'btn_signup result_new_btn' %>
                </div>
            </div>
        <% end %>
    </div>
</body>

app/views/testresults/notestresult.html.erb
<body class="result_body">

    <div class="search_group">
        <p class="search_title">定期試験結果未提出者検索</p>
        <form method="get" action="/notestresults">
            <select name="grade_keyword" class="search_box">
                <option value="">選択してください(学年)</option>
                <option value="1">1年</option>
                <option value="2">2年</option>
                <option value="3">3年</option>
            </select>
            <select name="test_keyword" class="search_box">
                <option value="">選択してください(学期)</option>
                <% @tests.each do |test| %>
                    <option value="<%= test.id %>"><%= test.test %></option>
                <% end %>
            </select>
            <p>
                <input type="submit" value="検索" class="search_btn">
                <%= link_to "一覧表示", alltestresults_path, class: "search_btn" %>
            </p>
        </form>
    </div>
    
    <div class="menu_group">
        <%= link_to "定期試験結果検索", noresults_path, class: "report_menu_item" %>
    </div>
    
    <% if @searchparameters.present? %>
        <p class="all_result_title"><%= @searchparameters[0]%>年　<%= @searchparameters[1]%>　の未提出者</p>
    <% end %>
    <div class="all_result">
        <% if @none_students.present? %>
            <table border="1" class="noresult_table">
                <thead>
                    <tr>
                        <th>生徒ID</th>
                        <th>生徒氏名</th>
                    </tr>
                </thead>
                <tbody>
                    <% @none_students.each do |none_student| %>
                    <tr>
                        <td><%= none_student.id %></td>
                        <td><a href="/students/<%= none_student.id %>" class="result_student_link"><%= none_student.student_info %></a></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        <% end %>
    </div>
</div>