config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'mains#index'
    
    resources :users, only: [:show, :index]
    resources :reports, only: [:index, :new, :create, :edit, :update, :destroy] 
    resources :schools, only: [:index, :create]
    resources :students, only: [:index, :create ,:show, :edit, :update]
    resources :results, only: [:index, :new, :create, :edit, :update]
    get 'allresults' => 'results#allresult'
    get 'noresults' => 'results#noresult'
    resources :testresults, only: [:index, :new, :create, :edit, :update]
    get 'alltestresults' => 'testresults#alltestresult'
    get 'notestresults' => 'testresults#notestresult'
    resources :targets, only: [:new, :create, :destroy]
    resources :ittoexams, only: [:index, :new, :create, :edit, :update]
    resources :highfiles, only: [:new, :create, :destroy, :show]
end

app/models/classifying.rb
class Classifying < ApplicationRecord
  has_many :reports, dependent: :delete_all
end

app/models/highfile.rb
class Highfile < ApplicationRecord
  belongs_to :user
  belongs_to :student
  
  validates :student_id, presence: true
  mount_uploader :image, HighfileUploader
end

app/models/ittoexam.rb
class Ittoexam < ApplicationRecord
  belongs_to :user
  belongs_to :student
  
  validates :year, presence: true
  validates :month, presence: true
  validates :student_id, presence: true
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :student
  belongs_to :user
  belongs_to :subject
  belongs_to :classifying
  
  validates :student_id, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  belongs_to :student
  belongs_to :semester
  
  validates :student_id, presence: true
  validates :grade, presence: true
  validates :semester_id, presence: true
end

app/models/school.rb
class School < ApplicationRecord
  has_many :students, dependent: :delete_all
end

app/models/semester.rb
class Semester < ApplicationRecord
  has_many :results, dependent: :delete_all
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :school
  belongs_to :student_type
  has_many :reports, dependent: :delete_all
  has_many :results, dependent: :delete_all
  has_many :testresults, dependent: :delete_all
  has_many :targets, dependent: :delete_all
  has_many :ittoexams, dependent: :delete_all
  
  validates :school_id, presence: true
  validates :student_type_id, presence: true
  validates :grade, presence: true
  validates :classifying, presence: true
  validates :family_name, presence: true
  validates :given_name, presence: true
  validates :family_name_kana, presence: true
  validates :given_name_kana, presence: true

  
  def name
    "#{family_name} #{given_name}"
  end

  def name_kana
    "#{family_name_kana}　#{given_name_kana}"
  end

  def student_info
    # case classifying
    # when  1
    #   classifying_detail = '小'
    # when 2
    #   classifying_detail = '中'
    # when 3
    #   classifying_detail = '高'
    # else
    #   classifying_detail = '非'
    # end
    
    classifying_detail = if classifying == 1
                           '小'
                         elsif classifying == 2
                           '中'
                         elsif classifying == 3
                           '高'
                         else
                           '非'
                         end

    "#{classifying_detail}　#{grade}年　#{family_name} #{given_name}"
  end
end

app/models/student_type.rb
class StudentType < ApplicationRecord
  has_many :students, dependent: :delete_all
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :reports, dependent: :delete_all
end

app/models/target.rb
class Target < ApplicationRecord
  belongs_to :user
  belongs_to :student
  
  validates :student_id, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  has_many :testresults, dependent: :delete_all
end

app/models/testresult.rb
class Testresult < ApplicationRecord
  belongs_to :user
  belongs_to :student
  belongs_to :test
  
  validates :student_id, presence: true
  validates :grade, presence: true
  validates :test_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :reports, dependent: :delete_all
  has_many :results, dependent: :delete_all
  has_many :testresults, dependent: :delete_all
  has_many :targets, dependent: :delete_all
  has_many :ittoexams, dependent: :delete_all
  has_many :highfiles, dependent: :delete_all

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :name, presence: true
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  def index; end
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/mains/index.html.erb
<body class="main_body">
    <h2 class="main_menu_title">メインメニュー</h2>
    <div class="menu_table">
        <div class="main_menu_table">
            <%= link_to "授業報告", reports_path, class: "menu_item" %><br>
            <%= link_to "ITTO模試(小中)", ittoexams_path, class: "menu_item" %><br>
            <%= link_to "通知表(中)", results_path, class: "menu_item" %><br>
            <%= link_to "定期試験(中)", testresults_path, class: "menu_item" %><br>
            <%= link_to "単語テスト(高)", new_target_path, class: "menu_item" %><br>
            <%= link_to "成績・面談(高)", new_highfile_path, class: "menu_item" %>
        </div>
        <div class="main_menu_table">
            <%= link_to "学校追加", schools_path, class: "menu_item" %><br>
            <%= link_to "生徒追加", students_path, class: "menu_item" %><br>
            <%= link_to "※︎通知表一覧(中)", allresults_path, class: "menu_item" %><br>
            <%= link_to "※︎定期試験一覧(中)", alltestresults_path, class: "menu_item" %><br>
            <%= link_to "︎講師一覧", users_path, class: "menu_item" %>
        </div>
    </div>
    <div class="main_intro">
        <ul class="main_intro_item">
            <li>色がついているところ、ボタンぽいところはクリック可能です。</li>
            <li>生徒情報は生徒の名前をクリック</li>
            <li>自分の情報は右上のマイページをクリック</li><br>
            <li>※一覧は生徒が周りにいない時に見てください。</li>
        </ul>
</body>    