config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'mains#index'
    
    resources :users, only: [:show, :index]
    resources :reports, only: [:index, :new, :create, :edit, :update, :destroy] 
    resources :schools, only: [:index, :create]
    resources :students, only: [:index, :create ,:show, :edit, :update]
    resources :results, only: [:index, :new, :create, :edit, :update]
    get 'allresults' => 'results#allresult'
    get 'noresults' => 'results#noresult'
    resources :testresults, only: [:index, :new, :create, :edit, :update]
    get 'alltestresults' => 'testresults#alltestresult'
    get 'notestresults' => 'testresults#notestresult'
    resources :targets, only: [:new, :create, :destroy]
    resources :ittoexams, only: [:index, :new, :create, :edit, :update]
    resources :highfiles, only: [:new, :create, :destroy, :show]
end

app/models/classifying.rb
class Classifying < ApplicationRecord
  has_many :reports, dependent: :delete_all
end

app/models/highfile.rb
class Highfile < ApplicationRecord
  belongs_to :user
  belongs_to :student
  
  validates :student_id, presence: true
  mount_uploader :image, HighfileUploader
end

app/models/ittoexam.rb
class Ittoexam < ApplicationRecord
  belongs_to :user
  belongs_to :student
  
  validates :year, presence: true
  validates :month, presence: true
  validates :student_id, presence: true
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :student
  belongs_to :user
  belongs_to :subject
  belongs_to :classifying
  
  validates :student_id, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  belongs_to :student
  belongs_to :semester
  
  validates :student_id, presence: true
  validates :grade, presence: true
  validates :semester_id, presence: true
end

app/models/school.rb
class School < ApplicationRecord
  has_many :students, dependent: :delete_all
end

app/models/semester.rb
class Semester < ApplicationRecord
  has_many :results, dependent: :delete_all
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :school
  belongs_to :student_type
  has_many :reports, dependent: :delete_all
  has_many :results, dependent: :delete_all
  has_many :testresults, dependent: :delete_all
  has_many :targets, dependent: :delete_all
  has_many :ittoexams, dependent: :delete_all
  
  validates :school_id, presence: true
  validates :student_type_id, presence: true
  validates :grade, presence: true
  validates :classifying, presence: true
  validates :family_name, presence: true
  validates :given_name, presence: true
  validates :family_name_kana, presence: true
  validates :given_name_kana, presence: true

  
  def name
    "#{family_name} #{given_name}"
  end

  def name_kana
    "#{family_name_kana}　#{given_name_kana}"
  end

  def student_info
    # case classifying
    # when  1
    #   classifying_detail = '小'
    # when 2
    #   classifying_detail = '中'
    # when 3
    #   classifying_detail = '高'
    # else
    #   classifying_detail = '非'
    # end
    
    classifying_detail = if classifying == 1
                           '小'
                         elsif classifying == 2
                           '中'
                         elsif classifying == 3
                           '高'
                         else
                           '非'
                         end

    "#{classifying_detail}　#{grade}年　#{family_name} #{given_name}"
  end
end

app/models/student_type.rb
class StudentType < ApplicationRecord
  has_many :students, dependent: :delete_all
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :reports, dependent: :delete_all
end

app/models/target.rb
class Target < ApplicationRecord
  belongs_to :user
  belongs_to :student
  
  validates :student_id, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  has_many :testresults, dependent: :delete_all
end

app/models/testresult.rb
class Testresult < ApplicationRecord
  belongs_to :user
  belongs_to :student
  belongs_to :test
  
  validates :student_id, presence: true
  validates :grade, presence: true
  validates :test_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :reports, dependent: :delete_all
  has_many :results, dependent: :delete_all
  has_many :testresults, dependent: :delete_all
  has_many :targets, dependent: :delete_all
  has_many :ittoexams, dependent: :delete_all
  has_many :highfiles, dependent: :delete_all

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :name, presence: true
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    if params[:user_keyword].present? and params[:student_keyword].present?
      reports = Report.where(user_id: params[:user_keyword]).order(created_at: :DESC).includes(:student, :user, :subject, :classifying).page(params[:page]).per(5)
      @reports = reports.where(student_id: params[:student_keyword]).order(created_at: :DESC).includes(:student, :user, :subject, :classifying).page(params[:page]).per(5)
    elsif params[:user_keyword].present? and params[:student_keyword].blank?
      @reports = Report.where(user_id: params[:user_keyword]).order(created_at: :DESC).includes(:student, :user, :subject, :classifying).page(params[:page]).per(5)
    elsif params[:user_keyword].blank? and params[:student_keyword].present?
      @reports = Report.where(student_id: params[:student_keyword]).order(created_at: :DESC).includes(:student, :user, :subject, :classifying).page(params[:page]).per(5)
    else
      @reports = Report.all.order(created_at: :DESC).includes(:student, :user, :subject, :classifying).page(params[:page]).per(5)
    end

    @users = User.all
    @students = Student.all.order(classifying: :ASC, grade: :ASC, family_name_kana: :ASC)
  end

  def new
    @report = Report.new
    if params[:student].present? and params[:classifying].present? and params[:subject]
      @parameters = [params[:student], params[:classifying], params[:subject]]
    end
  end

  def create
    Report.create(create_params)
    redirect_to reports_path
  end

  def edit
    @report = Report.find(params[:id])
  end

  def update
    report = Report.find(params[:id])
    report.update(update_params)
    redirect_to reports_path
  end

  def destroy
    report = Report.find(params[:id])
    if report.user_id == current_user.id
      report.destroy
    end
    redirect_to reports_path
  end

  private

    def create_params
      params.require(:report).permit(:classifying_id, :student_id, :subject_id, :report, :understanding).merge(user_id: current_user.id)
    end

    def update_params
      params.require(:report).permit(:classifying_id, :student_id, :subject_id, :report, :understanding).merge(user_id: current_user.id)
    end
end

app/helpers/highfiles_helper.rb
module HighfilesHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reports/_report.html.erb
<li class="report">
    <div class="report_info">
        <div class="report_info_first_line">
            <div class="report_info_first_line_left">
                <a href="/students/<%= report.student_id %>" class="report_info_item report_name"><%= report.student.family_name %></a>
                <a href="/students/<%= report.student_id %>" class="report_info_item report_name"><%= report.student.given_name %></a>
                <a class="report_info_item"><%= report.classifying.classifying %></a>
                <a class="report_info_item report_user"><%= report.user.name %></a>
                <a class="report_info_item"><%= report.subject.subject %></a>
                <a class="report_info_item"><%= report.created_at.to_s(:datetime_jp) %></a>
            </div>
            <div class="report_info_first_line_right">
                <% if report.user_id == current_user.id %>
                    <%= link_to "編集", edit_report_path(report.id), class: "report_info_link" %>
                    <%= link_to "削除", report_path(report.id), method: :delete, class: "report_info_link" %>
                <% else %>
                <% end %>
            </div>
        </div>
        <a >理解度</a>
        <a class="star5_rating" data-rate="<%= report.understanding %>"></a>
        <a ><%= report.understanding %></a>
    </div>
    <a class="report_report"><%= report.report %></a>
</li>

app/views/reports/edit.html.erb
<body class="report_new_body">
 
    <div class="report_form">
        <%= form_for @report do |f| %>
            <div class="report_form_group">
                <p class="search_title">授業報告編集</p>
            </div>
            <div class="report_form_group">
                <%= f.label :classifying_id, '種別'%>
                <% if @parameters.present? %>
                    <%= f.collection_select :classifying_id, Classifying.all, :id, :classifying, {include_blank: '選択してください', selected: @parameters[1]}, { class: 'form-control' , required: true }%>
                <% else %>
                    <%= f.collection_select :classifying_id, Classifying.all, :id, :classifying, {include_blank: '選択してください'}, { class: 'form-control' , required: true }%>
                <% end %>
            </div>
            <div class="report_form_group">
                <%= f.label :student_id, '生徒'%>
                <% if @parameters.present? %>
                    <%= f.collection_select :student_id, Student.all.order(classifying: :ASC, grade: :ASC, family_name_kana: :ASC), :id, :name, {include_blank: '選択してください', selected: @parameters[0]}, { class: 'form-control' , required: true }%>
                <% else %>
                    <%= f.collection_select :student_id, Student.all.order(classifying: :ASC, grade: :ASC, family_name_kana: :ASC), :id, :student_info, {include_blank: '選択してください'}, { class: 'form-control' , required: true }%>
                <% end %>
            </div>
            <div class="report_form_group">
                <%= f.label :subject_id, '教科'%>
                <% if @parameters.present? %>
                    <%= f.collection_select :subject_id, Subject.all, :id, :subject, {include_blank: '選択してください', selected: @parameters[2]}, { class: 'form-control' , required: true }%>
                <% else %>
                    <%= f.collection_select :subject_id, Subject.all, :id, :subject, {include_blank: '選択してください'}, { class: 'form-control' , required: true }%>
                <% end %>
            </div>
            <div class="report_form_group">
                <%= f.label :report, '本文'%><br>
                <%= f.text_area :report, class: 'form-control report_form_group_report', required: true %>
            </div>
            <div class="report_form_group">
                <%= f.label :understanding, '理解度'%>
                <%= f.radio_button :understanding, "1" , required: true %>1
                <%= f.radio_button :understanding, "2" %>2
                <%= f.radio_button :understanding, "3" %>3
                <%= f.radio_button :understanding, "4" %>4
            </div>
            <div class="report_form_group">
                <%= f.submit '送信', class: 'btn_signup' %>
            </div>
        <% end %>
    </div>
</body>
    

app/views/reports/index.html.erb
<body class="report_body">
    <div class="search_group">
        <p class="search_title">授業報告検索</p>
        <form method="get" action="/reports">
            <select name="user_keyword" class="search_box">
                <option value="">選択してください(講師)</option>
                <% @users.each do |user| %>
                    <option value="<%= user.id %>"><%= user.name %></option>
                <% end %>
            </select>
            <select name="student_keyword" class="search_box">
                <option value="">選択してください(生徒)</option>
                <% @students.each do |student| %>
                    <option value="<%= student.id %>"><%= student.student_info %></option>
                <% end %>
            </select>
            <p>
                <input type="submit" value="検索" class="search_btn">
                <%= link_to "一覧表示", reports_path, class: "search_btn" %>
            </p>
        </form>
    </div>
    
    <div class="menu_group">
        <%= link_to "授業報告登録", new_report_path, class: "report_menu_item" %>
    </div>
    
    <div class="report_group">
        <ul class="all_report">
            <%= render @reports %>
        </ul>
    </div>
    <div class="paginate"><%= paginate(@reports) %></div>
</body>

app/views/reports/new.html.erb
<body class="report_new_body">
 
    <div class="report_form">
        <%= form_for @report do |f| %>
            <div class="report_form_group">
                <p class="search_title">授業報告登録</p>
            </div>
            <div class="report_form_group">
                <%= f.label :classifying_id, '種別'%>
                <% if @parameters.present? %>
                    <%= f.collection_select :classifying_id, Classifying.all, :id, :classifying, {include_blank: '選択してください', selected: @parameters[1]}, { class: 'form-control' , required: true }%>
                <% else %>
                    <%= f.collection_select :classifying_id, Classifying.all, :id, :classifying, {include_blank: '選択してください'}, { class: 'form-control' , required: true }%>
                <% end %>
            </div>
            <div class="report_form_group">
                <%= f.label :student_id, '生徒'%>
                <% if @parameters.present? %>
                    <%= f.collection_select :student_id, Student.all.order(classifying: :ASC, grade: :ASC, family_name_kana: :ASC), :id, :name, {include_blank: '選択してください', selected: @parameters[0]}, { class: 'form-control' , required: true }%>
                <% else %>
                    <%= f.collection_select :student_id, Student.all.order(classifying: :ASC, grade: :ASC, family_name_kana: :ASC), :id, :student_info, {include_blank: '選択してください'}, { class: 'form-control' , required: true }%>
                <% end %>
            </div>
            <div class="report_form_group">
                <%= f.label :subject_id, '教科'%>
                <% if @parameters.present? %>
                    <%= f.collection_select :subject_id, Subject.all, :id, :subject, {include_blank: '選択してください', selected: @parameters[2]}, { class: 'form-control' , required: true }%>
                <% else %>
                    <%= f.collection_select :subject_id, Subject.all, :id, :subject, {include_blank: '選択してください'}, { class: 'form-control' , required: true }%>
                <% end %>
            </div>
            <div class="report_form_group">
                <%= f.label :report, '本文'%><br>
                <%= f.text_area :report, class: 'form-control report_form_group_report', required: true %>
            </div>
            <div class="report_form_group">
                <%= f.label :understanding, '理解度'%>
                <%= f.radio_button :understanding, "1" , required: true %>1
                <%= f.radio_button :understanding, "2" %>2
                <%= f.radio_button :understanding, "3" %>3
                <%= f.radio_button :understanding, "4" %>4
            </div>
            <div class="report_form_group">
                <%= f.submit '送信', class: 'btn_signup' %>
            </div>
        <% end %>
    </div>
</body>
    